### ISSUE TITLE
Support for Coq v8.8

### ISSUE THREAD

**Issue by tchajed** [uwplse/CoqAST#3]
We tend to use the latest version of Coq and it would be great to have CoqAST as an example. I started fixing compatibility issues at [tchajed/CoqAST (v8.8 branch)](https://github.com/tchajed/CoqAST/tree/v8.8) - if someone else has some expertise with writing Coq plugins, especially with multiple Coq versions, I'd appreciate help with the conversion!

**Comment by tlringer** [comment]
I think we tried to update this to Coq 8.8 already. Did the latest master version not work for you on 8.8?

**Comment by tlringer** [comment]
See: https://github.com/uwplse/CoqAST/commit/612d277523ef8fa2a372682b61f4d59ae6fda66e

**Comment by tchajed** [comment]
Oh nice! I didn't see that you had tackled this since I worked on it. Looks like it works on Coq v8.8.2 but something changed recently and it doesn't build with Coq v8.9 or Coq master:

```
File "src/ast_plugin.ml4", line 439, characters 28-44:
Error: Unbound type constructor mutual_inductive
```
